### ISSUE TITLE
Cities with a hyphen return 404

### ISSUE THREAD

**Issue by lesander** [lieuwex/VAKANTIE#1]
Hi Lieuwe,

It seems that any city which has a non-alphabetical character in it's name, isn't recognised by the server.

All supported cities can be found in the [`json/`](https://github.com/lieuwex/VAKANTIE/blob/master/json/) folder right? So entering a city on [vakantie.lieuwe.xyz](http://vakantie.lieuwe.xyz) with a `-`; for example `midden-delfland` or `s-hertogenbosch` should work OK, right?

Maybe this has something to do with the regex in [`main.coffee`@L53](https://github.com/lieuwex/VAKANTIE/blob/master/main.coffee#L53)

-- Sander

**Comment by lieuwex** [comment]
Thanks for the report @lesander! It should be fixed now.
